modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/catboybinary/scavenger/issues"
license = "GPLv3"

[[mods]]
modId = "scavenger"
version = "${version}"
displayName = "Scavenger"
authors = "catboybinary"
description = '''
A mod for interesting item speedruns with additional modifiers.
'''
logoFile = "icon.png"

[[dependencies.scavenger]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.scavenger]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.scavenger]]
modId = "architectury"
type = "required"
versionRange = "[19.0.1,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "scavenger.mixins.json"
